src/games/darksouls/addon.cpp, src/games/darksouls/bloom_0x6FDD08FC.ps_5_0.hlsl, src/games/darksouls/dof_far_0xDFCB6E8B.ps_5_0.hlsl, src/games/darksouls/gamma_0xAB7CF260.ps_5_0.hlsl, src/games/darksouls/shared.h, src/games/darksouls/tonemap_0xF87B3349.ps_5_0.hlsl, src/games/darksouls/ui_0x64F62639.ps_5_0.hlsl, src/games/darksouls/ui_0x809881A3.ps_5_0.hlsl, src/games/darksouls/ui_0xB0850BF3.ps_5_0.hlsl, src/games/darksouls/ui_text_0x6024AB96.ps_5_0.hlsl
- HDR scRGB support
- Sliders for depth of field and bloom adjustment
- 2.2 gamma correction
- New tonemappers: ACES, RenoDRT, and untonemapped output
- Adjustments for the strength of the game's color filters
- A hue correction toggle that allows other tonemappers to emulate the hue shifting from the vanilla tonemapper
- Full BT.2020 output
- Various color grading options, including sliders for exposure, highlights, contrast, saturation, and shadows
=> Add Support for Dark Souls: Remastered

src/devkit/addon.cpp, src/utils/shader_compiler.hpp
- Fix live code tab not showing the shader code until you clicked on another shader and back on the one you wanted to see.
- Added shader live replacement (as in, any time a new shader is created by the game, if we already have a custom file matching its hash, we immediately replace it without needing to click the "Load Shaders" button again).
- Added shader auto dumping (as in, any time a new shader is created by the game, it's immediately dumped).
- Show the name the user gave to a shader next to a shader hash when tracing.
- Show shader compile error in the trace live view. Also paint the text red if they failed to compile, and paint them green in their list if they were correctly replaced.
- Automatically append the shader type name to the dumped cso files (e.g. …
=> Many usability features

src/shaders/math.hlsl
The days of writing out the same formula for gamma encoding is over!
`color = renodx::math::safePow(color)` is the same as `color = sign(color) * pow(abs(color), 2.2f)` -- and you can set a custom exponent as the second argument; so 2.4 gamma would be `color = renodx::math::safePow(color, 2.4f)`
`color= renodx::math::pow(color)` = `color = pow(color, 2.2f)` -- custom gamma supported, same system as safePow
=> Add renodx::math::SafePow and renodx::math::Pow

src/games/darksouls/addon.cpp, src/games/darksouls/gamma_0xAB7CF260.ps_5_0.hlsl, src/games/darksouls/shared.h, src/games/darksouls/tonemap_0xF87B3349.ps_5_0.hlsl, src/games/darksouls/ui_0x64F62639.ps_5_0.hlsl, src/games/darksouls/ui_0x809881A3.ps_5_0.hlsl, src/games/darksouls/ui_0xB0850BF3.ps_5_0.hlsl, src/games/darksouls/ui_text_0x6024AB96.ps_5_0.hlsl
- **Tonemap Blending:** Added tonemap blending to allow custom tonemappers to blend with vanilla.
- **Color Grading Fix:** Resolved an issue where color grading applied post-tonemap did not respect peak luminance by utilizing the new `UpgradeToneMap()` function.
- **UI Blending Fix:** Corrected blending issues within the UI, ensuring a more consistent and visually appealing user interface.
- **Film Grain Slider Removal:** Removed the film grain slider, as the game already incorporates noise, reducing redundancy in graphical settings.
- **Hue Correction Update:** Implemented the new hue correction code, improving accuracy and consistency when emulating the hue shifting from the vanilla tonemapper.
=> Update Fallout 76 Support: Fix UI Blending, Fix Rendering Issues, Add New Features

src/games/dyinglight/addon.cpp, src/games/dyinglight/bloom_0x61D242D6.ps_5_0.hlsl, src/games/dyinglight/cap_0x8194877A.ps_5_0.hlsl, src/games/dyinglight/gamma_0x558540C8.ps_5_0.hlsl, src/games/dyinglight/godrays_0xA6EC1DEC.ps_5_0.hlsl, src/games/dyinglight/lensflare_0x3F53E66E.ps_5_0.hlsl, src/games/dyinglight/load_0x548937E1.ps_5_0.hlsl, src/games/dyinglight/lut1_0x372BEBAB.ps_5_0.hlsl, src/games/dyinglight/lut2_grain_0xC20255E1.ps_5_0.hlsl, src/games/dyinglight/lut2_no_grain_0xD42BAD58.ps_5_0.hlsl, src/games/dyinglight/lut_bw_grain_0x45D95DCB.ps_5_0.hlsl, src/games/dyinglight/lut_bw_no_grain_0xBA423838.ps_5_0.hlsl, src/games/dyinglight/shared.h, src/games/dyinglight/tonemap_0xA67ABF78.ps_5_0.hlsl, src/games/dyinglight/ui_0x23EFA382.ps_5_0.hlsl, src/games/dyinglight/ui_0x379D46ED.ps_5_0.hlsl, src/games/dyinglight/ui_0x404A04C7.ps_5_0.hlsl, src/games/dyinglight/ui_0x4D09799F.ps_5_0.hlsl, src/games/dyinglight/ui_0x637A1F5C.ps_5_0.hlsl, src/games/dyinglight/ui_0x6562755C.ps_5_0.hlsl, src/games/dyinglight/ui_0x7D5191F6.ps_5_0.hlsl, src/games/dyinglight/ui_0x7E8358E3.ps_5_0.hlsl, src/games/dyinglight/ui_0x822D56FA.ps_5_0.hlsl, src/games/dyinglight/ui_0x929C8CA5.ps_5_0.hlsl, src/games/dyinglight/ui_0x9F9A6B19.ps_5_0.hlsl, src/games/dyinglight/ui_0xB917BF4E.ps_5_0.hlsl, src/games/dyinglight/ui_0xBCBEE1E5.ps_5_0.hlsl, src/games/dyinglight/ui_0xD292312D.ps_5_0.hlsl, src/games/dyinglight/ui_0xDC15A986.ps_5_0.hlsl
This pull request introduces HDR support to Dying Light, which previously did not support HDR. Key enhancements include upgrading render targets, upgrading the swapchain, and adding various tonemapping and color grading options to provide a more immersive and visually appealing experience.
1. **HDR Support**:
- Upgraded clamped render targets to `RGBA16` format to accommodate HDR data.
- Upgraded the swapchain to `scRGB`, enabling full HDR10 output and better color accuracy.
2. **Tonemapping Options**:
- Added three distinct tonemapping options:
- **Vanilla**: Retains the original SDR tonemapping.
- **None**: Disables tonemapping and LUT entirely, allowing for a raw HDR output.
- **Vanilla+ (DICE)**: Blends the original Vanilla tonemapping with DICE tonemapping, offering a balanced HDR …
=> Add Support for Dying Light

src/games/dyinglight/DICE.hlsl, src/games/dyinglight/addon.cpp, src/games/dyinglight/extendGamut.hlsl, src/games/dyinglight/gamma_0x558540C8.ps_5_0.hlsl, src/games/dyinglight/lut2_grain_0xC20255E1.ps_5_0.hlsl, src/games/dyinglight/lut2_no_grain_0xD42BAD58.ps_5_0.hlsl, src/games/dyinglight/lut_bw_grain_0x45D95DCB.ps_5_0.hlsl, src/games/dyinglight/lut_bw_no_grain_0xBA423838.ps_5_0.hlsl, src/games/dyinglight/shared.h, src/games/dyinglight/tonemap_0xA67ABF78.ps_5_0.hlsl
1. **User Color Grading Fix**:
- Fixed issues related to blowout being added as a parameter in the middle of the UserColorGrading function.
2. **Integration of New DICE Tonemapper**:
- Updated the mod to use a newer version of DICE tonemapper
3. **Gamut Expansion**:
- Added a new gamut expansion slider. Generates HDR colors (BT.2020) from bright saturated SDR (BT.709) ones.
4. **Optimization**:
- Removed the unused `LUTScaling` variable from the injected buffer.
These updates have been thoroughly tested to ensure compatibility and stability across various gameplay scenarios. The fixes and enhancements significantly improve the visual fidelity and customization options available to players using the HDR mod.
=> Fixes and Enhancements for Dying Light

src/games/darksouls/DICE.hlsl, src/games/darksouls/addon.cpp, src/games/darksouls/gamma_0xAB7CF260.ps_5_0.hlsl, src/games/darksouls/shared.h, src/games/darksouls/tonemap_0xF87B3349.ps_5_0.hlsl, src/games/darksouls/ui_0x64F62639.ps_5_0.hlsl, src/games/darksouls/ui_0x809881A3.ps_5_0.hlsl, src/games/darksouls/ui_0xB0850BF3.ps_5_0.hlsl, src/games/darksouls/ui_text_0x6024AB96.ps_5_0.hlsl
This pull request introduces a complete rewrite of the RenoDX addon, streamlining the user experience while building on previous HDR and color grading enhancements. Below are the key changes in this update:
- **Streamlined Settings**: 
- **Removed the Gamma Correction Option**: The game now always linearizes with 2.2 gamma. This simplifies the mod and ensures consistent results.
- **Removed Tonemap Blending Option**: Tonemap blending is now always enabled as part of the Vanilla+ (DICE) tonemapper, further simplifying the user experience.
- **Removed ACES and RenoDRT Tonemappers**: These tonemappers were not the right fit for this game. With DICE, the color grading aspect of tonemapping is applied before the game's color filter, allowing better control over artistic adjustments. Then, the …
=> Full Rewrite and Optimization of RenoDX for Dark Souls Remastered

src/games/gow2018/addon.cpp, src/games/gow2018/final_gamma_0xB59D6558.ps_5_0.hlsl, src/games/gow2018/game_pq_0x279D11F6.ps_5_0.hlsl, src/games/gow2018/lut_0x7818463E.ps_5_0.hlsl, src/games/gow2018/shared.h
This pull request introduces additional improvements and fixes for the HDR implementation in *God of War (2018)*, building on previous changes related to tonemapping, gamma correction, and brightness control. The new features and fixes further refine the HDR experience and offer expanded LUT support.
---
- **LUT Scaling**: Added functionality to scale LUTs that have raised black levels.
- **UI Brightness Fix**: Fixed an issue where UI brightness scaling affected peak brightness. Now, lowering UI brightness will not reduce the peak brightness of the game content.
- **Hue Emulation Position**: Moved the hue emulation process to occur after LUT application, improving parity between HDR and SDR.
- **scRGB Format**: Upgraded the pipeline to use scRGB format for better HDR support and color …
=> HDR Enhancements for God of War (2018)

src/utils/date.hpp, src/utils/settings.hpp
Hi, adding `IsoDate` to be available in addon.cpp
Included in utils/settings.hpp so it is ready for use.
=> ISO date format

src/shaders/color.hlsl, src/shaders/colorcorrect.hlsl
use component wise ternary operator for shader model 5.X and lower and select for above where it's possible
=> some clean up and performance improvements

src/games/rdr1/PSApplyHDR10PQGammaCorrect.0x56F79BAD.ps_6_0.hlsl, src/games/rdr1/PSMiniAdapt.0xE033AAAD.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxOptics_0xEEEE53C5.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftCutsceneDof.0x9761FB07.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftCutsceneDofOptics.0x632ABCB2.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftDof.0xCCC43328.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftDofOptics.0xE93AD74D.ps_6_0.hlsl, src/games/rdr1/PSRDR2Postfx_0x4EAF2BC7.ps_6_0.hlsl, src/games/rdr1/addon.cpp, src/games/rdr1/shared.h
This pull request extends the capabilities of the RenoDX HDR mod for Red Dead Redemption by introducing interactive sliders, allowing players to customize various HDR visual settings directly within the game.
- **New Slider Functionality**: Players can now adjust HDR visual settings in real-time using sliders due to the inclusion of `renodx::mods::shader::allow_multiple_push_constants = true;` in the addon.cpp file. This change enables the support for injected buffers, providing a more dynamic and user-controlled visual experience.
- **Tonemap Type Slider**: Introduces controls to select 3 different tonemap options:
- Vanilla
- Vanilla+ 
- Vanilla+ Boosted
- **Dynamic Display Mapping**: Implements the DICE tonemapper to adjust the output down to the display's peak nits.
This update also …
=> feat(rdr1): add tonemap type and peak brightness sliders

src/games/dyinglight/DICE.hlsl, src/games/dyinglight/RenoDRTSmoothClamp.hlsl, src/games/dyinglight/addon.cpp, src/games/dyinglight/gamma_0x558540C8.ps_5_0.hlsl, src/games/dyinglight/lut2_grain_0xC20255E1.ps_5_0.hlsl, src/games/dyinglight/lut2_no_grain_0xD42BAD58.ps_5_0.hlsl, src/games/dyinglight/lut_bw_grain_0x45D95DCB.ps_5_0.hlsl, src/games/dyinglight/lut_bw_no_grain_0xBA423838.ps_5_0.hlsl, src/games/dyinglight/tonemap_0xA67ABF78.ps_5_0.hlsl
This update brings several crucial enhancements to the Dying Light RenoDX HDR mod. It introduces more sophisticated color management and tonemapping techniques that improve overall image quality and color accuracy.
1. **Updated DICE Tonemapping:**
- The DICE tonemapper has been updated to the latest version from Pumbo's Prey mod, which includes bug fixes.
2. **Advanced LUT Sampling and Tonemapping Adjustments:**
- `RenoDRTSmoothClamp()` is now used for LUT sampling with `UpgradeToneMap()`, instead of DICE. Applying the SDR LUT using this results in much better retention in highlight details.
- Tonemapping has been moved to the very end of the pipeline, after gamma correction, ensuring that peak brightness is not changed after tonemapping.
- DICE `ShoulderStart` has been adjusted to better …
=> HDR Enhancements for Dying Light

src/games/re2remake/ConvertRec2020PS_0xAF0777E5.ps_6_5.hlsl, src/games/re2remake/LUTBlackCorrection.hlsl, src/games/re3remake/ConvertRec2020PS_0x52248E59.ps_6_5.hlsl, src/games/re3remake/LUTBlackCorrection.hlsl, src/games/re7/ConvertRec2020PS_0x52248E59.ps_6_5.hlsl, src/games/re7/LUTBlackCorrection.hlsl, src/games/re7/tonemap_0xAD20915B.ps_6_5.hlsl
- sRGB -> 2.2 Gamma Correction has been added to Resident Evil 2, 3, and 7
- RenoDRTSmoothClamp() has been added to Resident Evil 7
- LUT Scaling has been modified to reduce black crush when paired with gamma correction
- DICE `ShoulderStart` has been increased as gamma correction lowers highlights
- Gamma Correction: The display I was originally using at the time of creating these mods was crushing blacks. Blacks are actually not crushed with 2.2 gamma correction. The gamma calibration menus in SDR also seem to imply 2.2 gamma is expected for these games.
- Adding `RenoDRTSmoothClamp()`: `RenoDRTSmoothClamp()` better preserves highlight detail, adding this to Resident Evil 7 brings it in line with the changes also made to Resident Evil 2, 3, and 4
=> Gamma Correction and Other Enhancements to Resident Evil 2, 3, and 7

src/games/re4remake/ConvertRec2020PS_0x6737588D.ps_6_6.hlsl, src/games/re4remake/LUTBlackCorrection.hlsl, src/games/re4remake/addon.cpp, src/games/re4remake/shared.h, src/games/re4remake/tonemap_inside_0x1F9104F3.ps_6_6.hlsl, src/games/re4remake/tonemap_outside_HDRPostProcess_WithTonemap_0x973A39FC.ps_6_6.hlsl
- sRGB -> 2.2 Gamma Correction has been added to Resident Evil 4 Remake
- The gamma adjustment slider is no longer by luminance, it is now by channel
- LUT Scaling has been modified to reduce black crush when paired with gamma correction
- DICE `ShoulderStart` has been increased as it was too low before and gamma correction also lowers highlights
- Gamma Correction: The display I was originally using at the time of creating these mods was crushing blacks. Blacks are actually not crushed with 2.2 gamma correction. The gamma calibration menus in SDR also seem to imply 2.2 gamma is expected for these games.
- Gamma Adjustment Slider: The gamma adjustment slider is now an alternative to gamma correction, as emulating 2.2 gamma often looks  crushed (though that seems to be the intention of the …
=> Gamma Correction for Resident Evil 4

src/games/bioshock/AntiAliasing_0xEC834D82.ps_4_0.hlsl, src/games/bioshock/Bloom_Tonemap_0x6457104F.ps_4_0.hlsl, src/games/bioshock/X_Final_0xFFFFFFFD.vs_5_0.hlsl, src/games/bioshock/X_Final_0xFFFFFFFE.ps_5_0.hlsl, src/games/bioshock/addon.cpp, src/games/bioshock/shared.h
Upgrading textures and removing a saturate() was all I had to do. The game was clipped, there was no tonemapping (and there still isn't). Bioshock 2 is probably the same.
Some of the render target textures are still not upgraded and are still R11G11B10F, unclear why.
=> Add Bioshock (Remastered)

src/games/batmanak/addon.cpp, src/games/rdr1/PSApplyHDR10PQGammaCorrect.0x56F79BAD.ps_6_0.hlsl, src/games/rdr1/PSMiniAdapt.0xE033AAAD.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxOptics_0xEEEE53C5.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftCutsceneDof.0x9761FB07.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftCutsceneDofOptics.0x632ABCB2.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftDof.0xCCC43328.ps_6_0.hlsl, src/games/rdr1/PSRDR2PostfxSoftDofOptics.0xE93AD74D.ps_6_0.hlsl, src/games/rdr1/PSRDR2Postfx_0x4EAF2BC7.ps_6_0.hlsl, src/games/rdr1/addon.cpp, src/games/rdr1/hueHelper.hlsl, src/games/rdr1/shared.h, src/games/rdr1/tonemaphelper.hlsl
**Red Dead Redemption:**
- add `RenoDRTSmoothClamp()` for use with `UpgradeToneMap()`
- add hue correction
- add links
- add build date and time
**Batman Arkham Knight:**
- add build date and time
- add tints to links
=> HDR Enhancements for Red Dead Redemption and minor improvements for Batman: Arkham Knight

src/games/dmc5/ConvertRec2020PS_0x6AB2B106.ps_5_0.hlsl, src/games/dmc5/DICE.hlsl, src/games/dmc5/LUTBlackCorrection.hlsl, src/games/dmc5/addon.cpp, src/games/dmc5/shared.h, src/games/dmc5/tonemap_0xA59B718D.ps_5_0.hlsl
This pull request enhances the HDR processing in Devil May Cry 5 by addressing fundamental flaws in the default tonemapping and color grading methods used in the game. It introduces critical improvements to LUT sampling and gamma to provide a more accurate and immersive HDR experience.
- **Refined Tonemapping**: Implemented a Vanilla+ tonemapper that correctly handles peak white levels, removing the default tonemapping's tendency to overshoot and subsequently clip highlights, which obscured details and degraded the visual quality.
- **Corrected Gamma**: Fixed the game's original gamma correction that was likely an attempt at emulating the sRGB -> 2.2 gamma correction. `renodx::color::correct::GammaSafe()` is now used for proper gamma correction.
- **Enhanced LUT Sampling**: Revamped the …
=> HDR Enhancements for Devil May Cry 5

src/shaders/color.hlsl
- add matrices to convert from "historical" standards to BT.709 D65
- add BT.709 D93 to BT.709 D65 matrix with chromatic adaptation
- update D65<->D60 CAT matrices with higher precision ones
"chromatic adaptation method: vK20" + "chromatic adaptation transform: CAT02" is the "newest shit" :D
=> feat(color): matrix stuff

src/shaders/tonemap.hlsl
Adds support for GTTonemap (Gran Turismo)
takes float and float3 inputs
https://www.desmos.com/calculator/gslcdxvipg
http://cdn2.gran-turismo.com/data/www/pdi_publications/PracticalHDRandWCGinGTS.pdf
```hlsl
// Uchimura 2018, "Practical HDR and Wide Color Techniques in Gran Turismo SPORT"
// https://www.desmos.com/calculator/gslcdxvipg
// http://cdn2.gran-turismo.com/data/www/pdi_publications/PracticalHDRandWCGinGTS.pdf
#define GTTONEMAP_GENERATOR(T)                \
T GTTonemap(T x,                            \
float P = 1.f,                  \
float a = 1.f,                  \
float m = 0.22f,                \
float l = 0.4f,                 \
float c = 1.33f,                \
float b = 0.f) {                \
float l0 = ((P - m) * l) / a;             \
float L0 = m - (m / a); …
```
=> feat(tonemap): add GTTonemap

src/games/scblacklist/addon.cpp, src/games/scblacklist/colorgrade_0x03DBB3FD.ps_5_0.hlsl, src/games/scblacklist/common.hlsl, src/games/scblacklist/final_0x1E767A42.ps_5_0.hlsl, src/games/scblacklist/lens_flare_0xB615F379.ps_5_0.hlsl, src/games/scblacklist/shared.h, src/games/scblacklist/sonar_0x81A1C030.ps_5_0.hlsl
This pull request integrates **Splinter Cell: Blacklist** with RenoDX by editing the game’s tonemap, sonar, and post-processing shaders. It adds **HDR** capabilities, extensive color grading controls, and a dedicated option to **tone map** the sonar goggles. Although Blacklist merges UI elements into its scene rendering (lens flare, sonar, etc.), this mod still allows for meaningful HDR customization.
1. **Tone Mapping Options**  
- **Vanilla**: Retains the original `saturate()`-based clamping.  
- **None**: Leaves the image unmodified (no compression).  
- **Exponential Rolloff**: Compresses highlights **above 1.0**, preserving the entire SDR range.  
- **Tone Map Sonar**: A toggle to clamp or apply Frostbite tonemapper to the sonar goggles.
2. **Color Grading Sliders**  
- **Exposure**, …
=> Add Splinter Cell: Blacklist Support to RenoDX

src/games/jedisurvivor/03_vignette_0x0B7B2D74.ps_6_1.hlsl, src/games/jedisurvivor/05_lower_vignette_0xD023A69B.ps_6_1.hlsl, src/games/jedisurvivor/08_lutbuilder_0x90BEE5D9.ps_6_1.hlsl, src/games/jedisurvivor/common.hlsl, src/games/jedisurvivor/shared.h
Jedi Survivor has now been updated to use the new defines, code has been cleaned up, and RenoDRT defaults have been configured to more closely match ACES.
=> refactor(jedisurvivor): use new defines, reconfigure RenoDRT

src/games/shadowtombraider/ACESLUT_0x2F759B36.cs_5_x.hlsl, src/games/shadowtombraider/addon.cpp, src/games/shadowtombraider/colorgrading_0x90C37605.cs_5_x.hlsl, src/games/shadowtombraider/common.hlsl, src/games/shadowtombraider/hdr_gamma_0x5D10D1A2.ps_4_0.hlsl, src/games/shadowtombraider/shared.h, src/games/shadowtombraider/tonemap_0x0FBDBDA4.ps_5_x.hlsl
This pull request enhances the HDR implementation in Shadow of the Tomb Raider by addressing issues with the vanilla tonemapper. The mod allows users to replace the broken ACES tonemapper, which had a high nit floor and clipped highlight detail, with alternative options for improved HDR performance and customization. It also disables the game's default brightness slider and introduces a custom slider with more precise controls.
1. **Custom Tonemapping Options**:
- **Vanilla**: Retains the original broken implementation of ACES tonemapper, this includes clipped highlight detail and raised blacks.
- **None**: Disables tonemapping entirely, allowing for raw HDR output.
- **RenoDRT**: Offers a refined HDR experience with better tone reproduction and customizable hue processing.
- **ACES**: …
=> HDR Enhancements for Shadow of the Tomb Raider

src/games/spidermanmilesmorales/addon.cpp, src/games/spidermanmilesmorales/common.hlsl, src/games/spidermanmilesmorales/include/ToneMapCB.hlsl, src/games/spidermanmilesmorales/shared.h, src/games/spidermanmilesmorales/tonemap_0xB5DBD65C.cs_6_6.hlsl, src/games/spidermanmilesmorales/tonemap_cAb_off_0xECBD5D23.cs_6_6.hlsl
- Overrides the gamma value for Spider-Man: Miles Morales to 2.2 instead of the original ~1.9 value
- There are no sliders as they resulted in crashes when ray tracing is enabled
- The project folder has been set up in a way that allows for sliders to easily be added
=> HDR Gamma Override for Spider-Man: Miles Morales

src/games/roadhogengine/DICE.hlsl, src/games/roadhogengine/addon.cpp, src/games/roadhogengine/common.hlsl, src/games/roadhogengine/gamma_0xC567CE8A.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/rip_0x23F2025E.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x2FF3AD78.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x38396D4E.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x39A21265.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x4338D617.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x45405040.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x5D1BC502.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x6AEB4E45.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x769FB187.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x79D405C5.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0x852CCF05.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xA6B01AE0.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xA8F9150B.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xAD092DF9.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xBA01D096.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xE29A7A29.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xE56AC1BF.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/tonemap_0xEF480D6C.ps_4_0.hlsl, src/games/roadhogengine/hardresetredux/videos_0x8FACEF64.ps_4_0.hlsl, src/games/roadhogengine/shared.h, src/games/roadhogengine/swap_chain_proxy_pixel_shader.ps_5_0.hlsl, src/games/roadhogengine/swap_chain_proxy_vertex_shader.vs_5_0.hlsl
Adds native HDR support to Hard Reset Redux.
Note: addon may be updated in the future to support Shadow Warrior (2013), and eventually fix Shadow Warrior 2 existing HDR implementation, hence the name.
=> feat(roadhogengine): add Hard Reset Redux mod

src/games/cp2077/addon.cpp, src/games/risetombraider/addon.cpp, src/games/seaofstars/addon.cpp, src/games/tombraider2013/addon.cpp, src/games/tombraider2013de/addon.cpp, src/utils/swapchain.hpp
- Implements a reference white calculation based off of calculating the HLG inverse OETF at 75% input and deriving the reference white nits of that value with the HLG OOTF. This is the most accurate way to do it.
- Replace the old reference white calculations in all addons with this new one.
=> implement a global more accurate reference white calculation + replace it where it was used before

src/games/unrealengine/addon.cpp
Infinity Nikki has issues with descriptor tables, causing the game to crash on start up, this makes the mod work again.
=> fix(unrealengine): fix infinity nikki crashing on start up

src/games/gowragnarok/addon.cpp, src/games/gowragnarok/bloom_0xF1E4F5FE.cs_6_6.hlsl, src/games/gowragnarok/calibration_0x4BB65477.ps_6_6.hlsl, src/games/gowragnarok/compute_bloom_0xC66F9B98.cs_6_6.hlsl, src/games/gowragnarok/final_0x903B49C1.ps_6_6.hlsl, src/games/gowragnarok/shared.h, src/games/gowragnarok/tonemap_0x4D780747.cs_6_6.hlsl
Fixes and improves the game's HDR rendering pipeline by correcting PQ encoding, replacing broken exposure logic, and enabling accurate brightness scaling. Preserves the original tonemapper with optional `Vanilla+` enhancements, and adds configurable controls for exposure and bloom. Also bypasses the game’s flawed gamma correction logic for accurate contrast and black levels.
- Preserves the game's **vanilla tonemapper**.
- Adds `Vanilla+` mode:
- Disables the game’s built-in exposure logic.
- Adds a **new exposure slider** (`ColorGradeExposure`) for adjusting exposure cleanly when `Vanilla+` is enabled.
- Applies brightness scaling **after** tonemapping using `ToneMapGameNits` to preserve hue, contrast, and saturation.
- Dynamically recalculates `peak_nits` and `min_nits` based on gamma …
=> God of War: Ragnarok – HDR Tonemapping Fix & Improvements

src/shaders/color.hlsl
9300K + 8 MPCD is apparently what Japanese mastering CRTs used; it's pretty close to D93
=> feat(color): add matrix to convert from ARIB TR B9 primaries with 9300K + 8 MPCD white point to BT.709 D65

src/games/farcry5/addon.cpp, src/games/farcry5/common.hlsli, src/games/farcry5/shared.h
- fix midgray calculation when using `Vanilla+` tonemapper
- add `ACES` tonemapper
- disable gamma correction slider with `Vanilla` tonemapper
- set `scene grading scaling` default to 75
=> feat(farycry5): use inverse midgray calculation for exposure matching

src/games/unrealengine/addon.cpp
Add pipeline signature exceptions for:
- Runescape: Dragon Wilds
- Enotria: The Last song
=> fix(unrealengine): Fix startup crash in multiple games

src/games/baldursgate3/addon.cpp, src/games/baldursgate3/shared.h, src/games/baldursgate3/tonemap_sample_lut_0x11C53BBA.ps_5_0.hlsl
- Use `log2()` as shaper for `ExponentialRollOff()`
- Add hue correction slider
- Add shoulder start slider
=> Baldur's Gate 3: Improved display mapping and hue correction 

src/games/unrealengine/addon.cpp
Add pipeline exceptions for:
- Satisfactory, EGS
- FATAL FURY: City of the Wolves
=> fix(unrealengine): Fix multiple games crash on startup

src/games/madmax/addon.cpp, src/games/madmax/output_dhc_0xB755AB0F.ps_5_0.hlsl, src/games/madmax/output_dhig_0xBEC13FF0.ps_5_0.hlsl, src/games/madmax/output_dhm_0x1FD18E12.ps_5_0.hlsl, src/games/madmax/output_dhs_0xF6A0E5D2.ps_5_0.hlsl, src/games/madmax/output_dnc_0x4DCDF058.ps_5_0.hlsl, src/games/madmax/output_dnig_0xDF35C719.ps_5_0.hlsl, src/games/madmax/output_dnm_0x569C5E86.ps_5_0.hlsl, src/games/madmax/output_dns_0xC39EC40D.ps_5_0.hlsl, src/games/madmax/output_fe_0x57CE885C.ps_5_0.hlsl, src/games/madmax/output_s_0x254ED214.ps_5_0.hlsl, src/games/madmax/shared.h, src/games/madmax/tonemap_ig_0x83FCCE5D.ps_5_0.hlsl, src/games/madmax/tonemap_menu_0x058D8234.ps_5_0.hlsl
turns out the shader that comes after outputs has tonemap at the end which caused highlights to become purple without bt709 clamp
=> feat(madmax): Add film grain + Fix highlights

src/games/ffxv/RenoDRTSmoothClamp.hlsl, src/games/ffxv/addon.cpp, src/games/ffxv/common.hlsl, src/games/ffxv/dithering_0x3F4687F4.ps_5_0.hlsl, src/games/ffxv/fmv_0x66EDB0A6.ps_5_0.hlsl, src/games/ffxv/glare_0xBBC1036C.ps_5_0.hlsl, src/games/ffxv/postprocessing_0xDD4C5B74.ps_5_0.hlsl, src/games/ffxv/postprocesssdr_0xD92625B9.ps_5_0.hlsl, src/games/ffxv/shared.h, src/games/ffxv/tonemap2_0x18EF8C72.ps_5_0.hlsl, src/games/ffxv/tonemap_0x75DFE4B0.ps_5_0.hlsl, src/games/ffxv/ui_0x369A4C39.ps_5_0.hlsl, src/games/ffxv/ui_0xB4EADB83.ps_5_0.hlsl, src/games/ffxv/ui_0xF2940481.ps_5_0.hlsl, src/games/ffxv/uisdr_0x19D2AC4F.ps_5_0.hlsl, src/games/ffxv/uisdr_0x4E3026D1.ps_5_0.hlsl, src/games/ffxv/uisdr_0xA12C8B65.ps_5_0.hlsl
The game HDR pipeline is SDR tonemapping -> SDR color grading -> brightness and saturation scaling without display mapping.
This PR rewrites the pipeline to get true HDR presentation:
- ToneMap to match midgray with the ungraded SDR, with respect to display peak brightness.
- Extend the color grading function, which controls saturation based on 4-band luminance, so the last band is now extended to RENODX_PEAK_NITS instead of SDR (1.0f) to get more saturation of bright elements.
- Add an option for "ApplyPerChannelCorrection" with respect to the untonemapped, to get more highlight saturation.
- SRGB decodes and inverse tonemaps pre-rendered videos.
=> feat(finalfantasyxv): rewrite HDR, extend color grading, add option to restore highlight saturation

src/games/ffxiv/addon.cpp
Game seems to use b8g8r8a8_unorm for it's RTV *only* if Gamma Correction is active, otherwise, it uses r8g8b8a8_unorm.
I don't know why the game does this, or since when it started doing this (it didn't do it on a previous version), but alas...
=> fix(ffxiv): upgrade b8g8r8a8_unorm to fix the mod w/ in-game gamma correction.

src/games/dyinglight/addon.cpp, src/games/dyinglight/gamma_0x558540C8.ps_5_0.hlsl, src/games/dyinglight/lens effects/lensflare2_0x7B8A6DC4.ps_5_0.hlsl, src/games/dyinglight/lens effects/lensflare_0x3F53E66E.ps_5_0.hlsl, src/games/dyinglight/lensflare2_0x7B8A6DC4.ps_5_0.hlsl, src/games/dyinglight/lighting/0x06A58024.ps_5_0.hlsl, src/games/dyinglight/lighting/0x1D09E8D5.ps_5_0.hlsl, src/games/dyinglight/lighting/0x50CFC334.ps_5_0.hlsl, src/games/dyinglight/lighting/0x5731A4EC.ps_5_0.hlsl, src/games/dyinglight/lighting/0x5B869E40.ps_5_0.hlsl, src/games/dyinglight/lighting/0x6ECA8248.ps_5_0.hlsl, src/games/dyinglight/lighting/0x7BF499C3.ps_5_0.hlsl, src/games/dyinglight/lighting/0x7C58E7EE.ps_5_0.hlsl, src/games/dyinglight/lighting/0x9FAA56D4.ps_5_0.hlsl, src/games/dyinglight/lighting/0xA12396FD.ps_5_0.hlsl, src/games/dyinglight/lighting/0xD690FC1B.ps_5_0.hlsl, src/games/dyinglight/lighting/fire_0xAB16B3F7.ps_5_0.hlsl, src/games/dyinglight/lighting/lighting.hlsli, src/games/dyinglight/lighting/lighting_0x45B99B2D.ps_5_0.hlsl, src/games/dyinglight/lighting/water_0x36E3A838.ps_5_0.hlsl, src/games/dyinglight/lighting/water_other_0xC24E43EF.ps_5_0.hlsl, src/games/dyinglight/shared.h, src/games/dyinglight/sky/godrays_0xA6EC1DEC.ps_5_0.hlsl, src/games/dyinglight/sky/sky_0x975AA892.ps_5_0.hlsl, src/games/dyinglight/sky/sunstar_0xBA89E3AC.ps_5_0.hlsl, src/shaders/math.hlsl
Dying Light:
- unclamp specular lighting
- unclamp fire brightness
- add luminance gamma correction
- adjust shadow and highlight slider behavior
- add new recommended settings
- brighten and increase sun size
Math:
- add float4 `DivideSafe()`
=> Unclamped Lighting and Other Enhancements for Dying Light

src/games/unrealengine/addon.cpp, src/games/unrealengine/games/thps3+4/lutbuilder_0xBF5C676F.ps_5_x.hlsl, src/games/unrealengine/games/thps3+4/lutbuilder_0xE73B3FFD.ps_5_x.hlsl, src/games/unrealengine/games/thps3+4/lutbuilder_0xEE1D0151.ps_5_x.hlsl
Fixed the incorrectly implemented demo lutbuilder. Moved it and the new ones to a game specific folder since the lutbuilders are definitely custom. Set swapchain_proxy_revert_state = true for the game to fix loading screens.
=> feat(unrealengine): fix thps3+4 demo and and release lutbuilders

src/shaders/colorcorrect.hlsl
add/adjust chrominance and hue functions
```cpp
float3 ChrominanceOKLab(float3 incorrect_color, float3 correct_color, float strength = 1.f) {
if (strength == 0.f) return incorrect_color;
float3 incorrect_lab = renodx::color::oklab::from::BT709(incorrect_color);
float3 correct_lab = renodx::color::oklab::from::BT709(correct_color);
float2 incorrect_ab = incorrect_lab.yz;
float2 correct_ab = correct_lab.yz;
// Compute chrominance (magnitude of the a–b vector)
float incorrect_chrominance = length(incorrect_ab);
float correct_chrominance = length(correct_ab);
// Scale original chrominance vector toward target chrominance
float chrominance_ratio = renodx::math::DivideSafe(correct_chrominance, incorrect_chrominance, 1.f);
float scale = lerp(1.f, chrominance_ratio, strength);
incorrect_lab.yz = …
```
=> feat(colorcorrect): add/adjust chrominance and hue functions

src/games/baldursgate3/common.hlsli, src/games/baldursgate3/shared.h, src/games/baldursgate3/tonemap_lutbuilder_alternate_0x1B418D49.cs_5_0.hlsl, src/games/baldursgate3/tonemap_lutbuilder_main_0x48E37C1E.cs_5_0.hlsl
- blend between RenoDRT for midtones and shadows and ACES for highlights
- use luminance gamma correction
=> Tone Mapping improvements for Baldur's Gate 3
